// components/Cards/ProjectCard/ProjectCard.tsx
import { ImLink } from 'react-icons/im';
import { SiGithub } from 'react-icons/si';
import { Project } from '../../../api/projects';
import classNames from '../../../helpers/classNames';
import { formatAsDate } from '../../../helpers/datetime';
import CommonCard from '../Common';

type Props = Project & { className?: string; withOverlay?: boolean };
export default function ProjectCard({
    title,
    date,
    description,
    source,
    url,
    className,
    languages,
    tech,
    withOverlay = false,
}: Props) {
    return (
        <CommonCard className={classNames(className)} withOverlay={withOverlay}>
            <header className="flex justify-between">
                <div>
                    <p className="text-sub text-sm dark:text-dark-sub m-0 mb-1">
                        {formatAsDate(date)}
                    </p>
                    <h3 className="m-0 mb-2">{title}</h3>
                </div>
                <div className="flex pt-1">
                    {source && (
                        <a
                            href={source}
                            className="mr-2 text-link dark:text-dark-link"
                            title="Github repository"
                        >
                            <SiGithub size="1.2rem" />
                        </a>
                    )}
                    {url && (
                        <a
                            href={url}
                            className="mr-2 text-link dark:text-dark-link"
                            title="Website link"
                        >
                            <ImLink size="1.2rem" />
                        </a>
                    )}
                </div>
            </header>
            <div className="overflow-hidden flex-shrink">{description}</div>
            {!withOverlay && (
                <div className="flex flex-wrap flex-row">
                    <div className="w-1/2">
                        <h3>Languages</h3>
                        <ul>
                            {languages.map((lang) => (
                                <li key={lang}>{lang}</li>
                            ))}
                        </ul>
                    </div>
                    <div className="w-1/2">
                        <h3>Tech</h3>
                        <ul>
                            {tech.map((tech) => (
                                <li key={tech}>{tech}</li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}
        </CommonCard>
    );
}

// components/project-card.vue
<template>
    <common-card class="c-project-card" :overlay="overlay">
        <template v-slot:header>
            <div class="c-project-card__header">
                <div class="c-project-card__title">
                    <p class="c-project-card__date">
                        {{ formattedDate }}
                    </p>
                    <h3>
                        {{ project.title }}
                    </h3>
                </div>

                <div class="c-project-card__links">
                    <a v-if="project.source" :href="project.source">
                        <font-awesome-icon
                            :icon="['fab', 'github']"
                        ></font-awesome-icon>
                    </a>
                    <a v-if="project.url" :href="project.url">
                        <font-awesome-icon
                            :icon="['fas', 'link']"
                        ></font-awesome-icon>
                    </a>
                </div>
            </div>
        </template>
        <div class="c-project-card__content">
            <p>{{ project.description }}</p>
            <div class="c-project-card__content__technologies">
                <h3>Languages</h3>
                <ul>
                    <li v-for="lang in project.languages" :key="lang">
                        {{ lang }}
                    </li>
                </ul>
            </div>

            <div class="c-project-card__content__technologies">
                <h3>Technologies</h3>
                <ul>
                    <li v-for="tech in project.tech" :key="tech">
                        {{ tech }}
                    </li>
                </ul>
            </div>
        </div>
    </common-card>
</template>
<script lang="ts">
import Vue from 'vue'
import { formatAsDate } from '~/helpers/datetime'

interface IProps {
    project: {
        title: string
        description: string
        date: string
        url: string
        source: string
        languages: string[]
        tech: string[]
    }
    overlay: boolean
}

export default Vue.extend<{}, {}, {}, IProps>({
    props: {
        project: {
            type: Object,
            required: true,
        },
        overlay: {
            type: Boolean,
            required: true,
        },
    },
    computed: {
        formattedDate() {
            return formatAsDate(this.project.date)
        },
    },
})
</script>

<style lang="scss" scoped>
.c-project-card {
    &.-overlay {
        @apply h-40;
        @apply overflow-hidden;
    }

    &__header {
        @apply flex justify-between;
    }
    &__links {
        @apply mr-2;
        @apply text-lg;
    }
    &__date {
        @apply m-0;
        @apply text-gray-600 text-sm;
    }
    &__title h3 {
        @apply font-bold;
        @apply m-0;
    }
    &__content {
        @apply pb-4;
        @apply flex flex-wrap;

        p {
            @apply w-full;
            @apply pb-6;
        }
        &__technologies {
            @apply w-1/2;

            h3 {
                @apply text-gray-600 font-medium;
            }

            ul {
                @apply mt-1;
            }
        }
    }
}
</style>
